version: '3.0'
services:
  test_api:
    build: .
    container_name: 'api_test'
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0"
    ports:
      - 8000:8000
    depends_on:
      postgres_test:
        condition: service_healthy
    volumes:
      - ./.env:/api/.env
    networks:
      - test_network
    env_file:
      - .env

  postgres_test:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_TEST_USER}
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD}
      POSTGRES_DB: ${DB_TEST}
      POSTGRES_HOST_AUTH_METHOD: ${DB_TEST_AUTH_METHOD}

    ports:
      - 5433:5432
    expose:
      - 5433
    networks:
      - test_network
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${DB_TEST} -U $${DB_TEST_USER}"]
      interval: 10s
      timeout: 30s
      retries: 5

networks:
  test_network:
    driver: bridge