"""empty message

Revision ID: d0d53dad4a09
Revises: 
Create Date: 2024-01-18 19:47:18.761866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0d53dad4a09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('menu_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('submenu_count', sa.Integer(), nullable=True),
    sa.Column('dishes_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('menu_id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('menu_id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('submenus',
    sa.Column('submenu_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('dishes_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.menu_id'], ),
    sa.PrimaryKeyConstraint('submenu_id'),
    sa.UniqueConstraint('submenu_id')
    )
    op.create_table('dishes',
    sa.Column('dish_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submenu_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['submenu_id'], ['submenus.submenu_id'], ),
    sa.PrimaryKeyConstraint('dish_id'),
    sa.UniqueConstraint('dish_id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dishes')
    op.drop_table('submenus')
    op.drop_table('menus')
    # ### end Alembic commands ###
