"""empty message

Revision ID: d76ba6f3d309
Revises: d0d53dad4a09
Create Date: 2024-01-18 20:18:23.008311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd76ba6f3d309'
down_revision: Union[str, None] = 'd0d53dad4a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'dishes', ['dish_id'])
    op.create_unique_constraint(None, 'menus', ['menu_id'])
    op.drop_column('menus', 'submenu_count')
    op.drop_column('menus', 'dishes_count')
    op.create_unique_constraint(None, 'submenus', ['submenu_id'])
    op.drop_column('submenus', 'dishes_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenus', sa.Column('dishes_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'submenus', type_='unique')
    op.add_column('menus', sa.Column('dishes_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('menus', sa.Column('submenu_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'menus', type_='unique')
    op.drop_constraint(None, 'dishes', type_='unique')
    # ### end Alembic commands ###
